#source 'https://github.com/CocoaPods/Specs.git'

platform  :ios, '11.0'
use_frameworks!

target 'KKMediaPickerFramework' do

end

target 'KKMediaPickerLibrary' do

end


target 'KKMediaPickerDemo' do

#  pod 'KeKeLibrary'
  pod 'KeKeMediaPicker', :path => '../../KeKeMediaPicker'

end
